language: android
jdk: oraclejdk8

android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used by your project
    - build-tools-29.0.3

    # The SDK version used to compile your project
    - android-28

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-28

  licenses:
    - 'android-sdk-license-.+'

before_install:
  - touch $HOME/.android/repositories.cfg
  # 29 is required to be accepted on both platform and tools despite the actual versions being used
  - yes | sdkmanager "platforms;android-29"
  - yes | sdkmanager "build-tools;29.0.3"
