package net.gotev.sipservice;

/**
 * Enumeration of the broadcast actions
 */
enum BroadcastAction {
    REGISTRATION,
    INCOMING_CALL,
    CALL_STATE,
    CALL_MEDIA_STATE,
    OUTGOING_CALL,
    STACK_STATUS,
    CODEC_PRIORITIES,
    CODEC_PRIORITIES_SET_STATUS,
    MISSED_CALL,
    VIDEO_SIZE,
    CALL_STATS,
    CALL_RECONNECTION_STATE,
    SILENT_CALL_STATUS,
    NOTIFY_TLS_VERIFY_STATUS_FAILED,
    CALLBACK_SET_ACCOUNT,
    CALLBACK_REMOVE_ACCOUNT,
    INCOMING_CALL_NOTIFICATION_CLICK,
    ACCEPT_INCOMING_CALL_ACTION,
    END_SERVICE_ACTION,
    CALL_MEDIA_EVENT,
    CALLBACK_GENERIC_ERROR
}