/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Parameters for Account::shutdown2().
 */
public class AccountShutdownParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AccountShutdownParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AccountShutdownParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AccountShutdownParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AccountShutdownParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * If true, the account will always be deleted even when there are<br>
   * active calls using it (a warning will be logged). If false, the<br>
   * function will throw an Error with PJ_EBUSY when active calls exist.<br>
   * <br>
   * Default: false
   */
  public void setForce(boolean value) {
    pjsua2JNI.AccountShutdownParam_force_set(swigCPtr, this, value);
  }

  /**
   * If true, the account will always be deleted even when there are<br>
   * active calls using it (a warning will be logged). If false, the<br>
   * function will throw an Error with PJ_EBUSY when active calls exist.<br>
   * <br>
   * Default: false
   */
  public boolean getForce() {
    return pjsua2JNI.AccountShutdownParam_force_get(swigCPtr, this);
  }

  /**
   *  Default constructor 
   */
  public AccountShutdownParam() {
    this(pjsua2JNI.new_AccountShutdownParam(), true);
  }

}
