/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * AI Media Port event data.
 */
public class AiMediaEvent {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AiMediaEvent(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AiMediaEvent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AiMediaEvent obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AiMediaEvent(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   *  Event type. 
   */
  public void setType(int value) {
    pjsua2JNI.AiMediaEvent_type_set(swigCPtr, this, value);
  }

  /**
   *  Event type. 
   */
  public int getType() {
    return pjsua2JNI.AiMediaEvent_type_get(swigCPtr, this);
  }

  /**
   *  Status code. PJ_SUCCESS for informational events. 
   */
  public void setStatus(int value) {
    pjsua2JNI.AiMediaEvent_status_set(swigCPtr, this, value);
  }

  /**
   *  Status code. PJ_SUCCESS for informational events. 
   */
  public int getStatus() {
    return pjsua2JNI.AiMediaEvent_status_get(swigCPtr, this);
  }

  /**
   *  Text payload (transcript). Only valid for TRANSCRIPT events. 
   */
  public void setText(String value) {
    pjsua2JNI.AiMediaEvent_text_set(swigCPtr, this, value);
  }

  /**
   *  Text payload (transcript). Only valid for TRANSCRIPT events. 
   */
  public String getText() {
    return pjsua2JNI.AiMediaEvent_text_get(swigCPtr, this);
  }

  public AiMediaEvent() {
    this(pjsua2JNI.new_AiMediaEvent(), true);
  }

}
