/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * AI Media Port creation parameters.
 */
public class AiMediaPortParam {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AiMediaPortParam(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AiMediaPortParam obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AiMediaPortParam obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AiMediaPortParam(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  /**
   * Enable voice activity detection (VAD) on the TX path.<br>
   * When enabled, silence frames are not sent to the AI service.<br>
   * <br>
   * Default: false
   */
  public void setVadEnabled(boolean value) {
    pjsua2JNI.AiMediaPortParam_vadEnabled_set(swigCPtr, this, value);
  }

  /**
   * Enable voice activity detection (VAD) on the TX path.<br>
   * When enabled, silence frames are not sent to the AI service.<br>
   * <br>
   * Default: false
   */
  public boolean getVadEnabled() {
    return pjsua2JNI.AiMediaPortParam_vadEnabled_get(swigCPtr, this);
  }

  /**
   * Ptime in milliseconds.<br>
   * <br>
   * Default: 20
   */
  public void setPtimeMsec(long value) {
    pjsua2JNI.AiMediaPortParam_ptimeMsec_set(swigCPtr, this, value);
  }

  /**
   * Ptime in milliseconds.<br>
   * <br>
   * Default: 20
   */
  public long getPtimeMsec() {
    return pjsua2JNI.AiMediaPortParam_ptimeMsec_get(swigCPtr, this);
  }

  /**
   *  Default constructor 
   */
  public AiMediaPortParam() {
    this(pjsua2JNI.new_AiMediaPortParam(), true);
  }

}
