/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * AI Media Port.<br>
 * <br>
 * This wraps pjmedia_ai_port as an AudioMedia object that can be<br>
 * connected to the conference bridge. It bridges audio to/from<br>
 * real-time AI services (e.g. OpenAI Realtime API) over WebSocket.<br>
 * <br>
 * Basic usage:<br>
 * 1. Create with createPort() (uses the OpenAI Realtime API backend).<br>
 * 2. Connect to the AI service with connect().<br>
 * 3. Use startTransmit()/stopTransmit() to route audio from/to<br>
 *    other conference bridge ports (e.g. AudioMedia from a call).<br>
 * 4. Disconnect with disconnect() when done.<br>
 * <br>
 * Events (connected, transcript, etc.) are delivered via the<br>
 * virtual onEvent() callback.
 */
public class AudioMediaAiPort extends AudioMedia {
  private transient long swigCPtr;

  protected AudioMediaAiPort(long cPtr, boolean cMemoryOwn) {
    super(pjsua2JNI.AudioMediaAiPort_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AudioMediaAiPort obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AudioMediaAiPort obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AudioMediaAiPort(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    pjsua2JNI.AudioMediaAiPort_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    pjsua2JNI.AudioMediaAiPort_change_ownership(this, swigCPtr, true);
  }

  @SuppressWarnings("this-escape")
  /**
   * Constructor.
   */
  public AudioMediaAiPort() {
    this(pjsua2JNI.new_AudioMediaAiPort(), true);
    pjsua2JNI.AudioMediaAiPort_director_connect(this, swigCPtr, true, true);
  }

  /**
   * Create an AI media port with the OpenAI Realtime API backend and<br>
   * register it to the conference bridge. The port operates at the<br>
   * backend's native clock rate (e.g. 24kHz for OpenAI); the<br>
   * conference bridge handles resampling.<br>
   * <br>
   * @param prm       Creation parameters.
   */
  public void createPort(AiMediaPortParam prm) throws Exception {
    pjsua2JNI.AudioMediaAiPort_createPort__SWIG_0(swigCPtr, this, AiMediaPortParam.getCPtr(prm), prm);
  }

  /**
   * Create an AI media port with the OpenAI Realtime API backend and<br>
   * register it to the conference bridge. The port operates at the<br>
   * backend's native clock rate (e.g. 24kHz for OpenAI); the<br>
   * conference bridge handles resampling.<br>
   * <br>
   * 
   */
  public void createPort() throws Exception {
    pjsua2JNI.AudioMediaAiPort_createPort__SWIG_1(swigCPtr, this);
  }

  /**
   * Connect to the AI service asynchronously. The onEvent() callback<br>
   * will be called with PJMEDIA_AI_EVENT_CONNECTED or<br>
   * PJMEDIA_AI_EVENT_DISCONNECTED when complete.<br>
   * <br>
   * @param url           WebSocket URL (e.g.<br>
   *                      "wss://api.openai.com/v1/realtime?model=...")<br>
   * @param authToken     Authentication token (e.g. OpenAI API key).
   */
  public void connect(String url, String authToken) throws Exception {
    pjsua2JNI.AudioMediaAiPort_connect(swigCPtr, this, url, authToken);
  }

  /**
   * Disconnect from the AI service gracefully.
   */
  public void disconnect() throws Exception {
    pjsua2JNI.AudioMediaAiPort_disconnect(swigCPtr, this);
  }

  /**
   * Called when an AI event occurs (connected, transcript, etc.).<br>
   * This may be called from the ioqueue worker thread.<br>
   * <br>
   * @param event     The event data.
   */
  public void onEvent(AiMediaEvent event) {
    if (getClass() == AudioMediaAiPort.class) pjsua2JNI.AudioMediaAiPort_onEvent(swigCPtr, this, AiMediaEvent.getCPtr(event), event); else pjsua2JNI.AudioMediaAiPort_onEventSwigExplicitAudioMediaAiPort(swigCPtr, this, AiMediaEvent.getCPtr(event), event);
  }

}
