/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

/**
 * Represents a pending authentication challenge.<br>
 * Call respond() to resend with authentication, or abandon() to give up.<br>
 * If neither is called before the callback returns, the library handles<br>
 * authentication automatically using configured credentials (sync path).<br>
 * <br>
 * For async use, call defer() during the callback to obtain a heap-allocated<br>
 * AuthChallenge that can be used later. The caller owns the returned object.<br>
 * <br>
 * Each AuthChallenge is single-use: once consumed by respond(), abandon(),<br>
 * or defer(), further calls return PJ_EINVALIDOP (defer() throws Error).<br>
 * <br>
 * Thread safety: on a deferred object, respond() and abandon() must be called<br>
 * from a pjlib-registered thread. The non-deferred object must only be used<br>
 * during the onAuthChallenge() callback.<br>
 * <br>
 * GC note (Python/Java): The destructor calls pjsip APIs which require a<br>
 * pjlib-registered thread. Since garbage collectors may run destructor/<br>
 * Release() on an unregistered finalizer thread, you MUST explicitly call<br>
 * respond(), abandon(), or delete/Release() on the deferred object from a<br>
 * pjlib-registered thread. Do NOT let the GC collect it implicitly.<br>
 * See https://docs.pjsip.org/en/latest/pjsua2/general_concept.html#problems-with-garbage-collection
 */
public class AuthChallenge {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AuthChallenge(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AuthChallenge obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected static long swigRelease(AuthChallenge obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings({"deprecation", "removal"})
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        pjsua2JNI.delete_AuthChallenge(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public AuthChallenge() {
    this(pjsua2JNI.new_AuthChallenge(), true);
  }

  /**
   * Defer the challenge for asynchronous handling. Creates a new<br>
   * heap-allocated AuthChallenge that can be used after the callback<br>
   * returns. The caller owns the returned object and must eventually<br>
   * call respond() or abandon() on it (or simply delete it, which<br>
   * auto-abandons).<br>
   * <br>
   * Must be called during the onAuthChallenge() callback. After this<br>
   * call, the original AuthChallenge becomes invalid.<br>
   * <br>
   * @return New heap-allocated AuthChallenge (caller owns).
   */
  public AuthChallenge defer() throws Exception {
    long cPtr = pjsua2JNI.AuthChallenge_defer(swigCPtr, this);
    return (cPtr == 0) ? null : new AuthChallenge(cPtr, true);
  }

  /**
   * Respond to the authentication challenge by building and sending<br>
   * an authenticated request. Uses credentials currently configured<br>
   * on the auth session.<br>
   * <br>
   * @return PJ_SUCCESS on success, or PJ_EINVALIDOP if already<br>
   *                  consumed by a prior respond()/abandon()/defer() call.
   */
  public int respond() {
    return pjsua2JNI.AuthChallenge_respond__SWIG_0(swigCPtr, this);
  }

  /**
   * Respond with provided credentials. Sets them on the account-level<br>
   * shared auth session before building the authenticated request.<br>
   * Note that this permanently replaces the account's credentials,<br>
   * affecting all subsequent authentication for the account.<br>
   * <br>
   * @param creds     Credentials to set on the auth session.<br>
   * @return PJ_SUCCESS on success.
   */
  public int respond(AuthCredInfoVector creds) {
    return pjsua2JNI.AuthChallenge_respond__SWIG_1(swigCPtr, this, AuthCredInfoVector.getCPtr(creds), creds);
  }

  /**
   * Abandon the authentication challenge. The pending request will<br>
   * not be resent.<br>
   * <br>
   * @return PJ_SUCCESS on success, or PJ_EINVALIDOP if already<br>
   *                  consumed by a prior respond()/abandon()/defer() call.
   */
  public int abandon() {
    return pjsua2JNI.AuthChallenge_abandon(swigCPtr, this);
  }

  /**
   * Check whether this challenge object is still valid (not yet<br>
   * consumed by respond() or abandon(), and the associated account<br>
   * is still active).<br>
   * <br>
   * Note: this is an advisory check without synchronization.<br>
   * The result may be stale if another thread concurrently<br>
   * deletes the account.<br>
   * <br>
   * @return true if valid.
   */
  public boolean isValid() {
    return pjsua2JNI.AuthChallenge_isValid(swigCPtr, this);
  }

}
