/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pj_file_access {
  public final static int PJ_O_RDONLY = 4353;
  public final static int PJ_O_WRONLY = 4354;
  public final static int PJ_O_RDWR = 4355;
  public final static int PJ_O_APPEND = 4360;
  public final static int PJ_O_CLOEXEC = 4356;
  public final static int PJ_O_ASYNC = 512;
  public final static int PJ_O_SEQUENTIAL = 1024;
  public final static int PJ_O_RANDOM = 2048;
}

