/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.4.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.pjsip.pjsua2;

public final class pjmedia_ai_event_type {
  public final static int PJMEDIA_AI_EVENT_CONNECTED = 0;
  public final static int PJMEDIA_AI_EVENT_DISCONNECTED = PJMEDIA_AI_EVENT_CONNECTED + 1;
  public final static int PJMEDIA_AI_EVENT_TRANSCRIPT = PJMEDIA_AI_EVENT_DISCONNECTED + 1;
  public final static int PJMEDIA_AI_EVENT_RESPONSE_START = PJMEDIA_AI_EVENT_TRANSCRIPT + 1;
  public final static int PJMEDIA_AI_EVENT_RESPONSE_DONE = PJMEDIA_AI_EVENT_RESPONSE_START + 1;
  public final static int PJMEDIA_AI_EVENT_SPEECH_STARTED = PJMEDIA_AI_EVENT_RESPONSE_DONE + 1;
  public final static int PJMEDIA_AI_EVENT_SPEECH_STOPPED = PJMEDIA_AI_EVENT_SPEECH_STARTED + 1;
}

